<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import {useForm, usePage} from "@inertiajs/vue3";
import {Button} from "@/Components/shadcn/ui/button/index.js";
import {Form, FormDescription, FormField, FormItem, FormLabel} from "@/Components/shadcn/ui/form/index.js";
import {Textarea} from "@/Components/shadcn/ui/textarea/index.js";
import {Card, CardContent, CardDescription, CardHeader, CardTitle} from "@/Components/shadcn/ui/card/index.js";
import InputError from "@/Components/InputError.vue";
import {Input} from "@/Components/shadcn/ui/input/index.js";
import {XCircleIcon} from '@heroicons/vue/16/solid'
import {BuildingStorefrontIcon, UserIcon} from '@heroicons/vue/24/solid'
import {cn} from "@/lib/utils.js";
import {RadioGroup, RadioGroupItem} from "@/Components/shadcn/ui/radio-group/index.js";
import {Label} from "@/Components/shadcn/ui/label/index.js";

const page = usePage()
const contact = page.props.contact

</script>

<template>
    <AppLayout title="Sendex">
        <div>
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="overflow-hidden">
                    <div class="flex-1 space-y-4 p-8 pt-6">
                        <div class="grid gap-6 md:grid-cols-1 lg:grid-cols-2">
                            <div>
                            <Card>
                                <CardHeader>
                                    <CardTitle>Contact Info</CardTitle>
                                    <CardDescription>
                                        Details of your contact
                                    </CardDescription>
                                </CardHeader>
                                <CardContent class="space-y-4">
                                    <div class="grid gap-2">
                                        <Label for="name">Name</Label>
                                        <Input id="name" :placeholder="contact.name" />
                                    </div>
                                    <div class="grid gap-2">
                                        <Label for="number">Email</Label>
                                        <Input id="number" :placeholder="contact.email" />
                                    </div>
                                    <div class="grid gap-2">
                                        <Label for="name">Phone</Label>
                                        <Input id="name" :placeholder="contact.phone" />
                                    </div>
                                    <div class="grid gap-2">
                                        <Label for="bio">Bio</Label>
                                        <Textarea :value="contact.bio" id="bio" :placeholder="contact.about" />
                                    </div>
                                    <div class="grid gap-2">
                                        <Label for="url">Urls</Label>
                                        <Input v-for="url in contact.data.urls" :key="url" :placeholder="url">
                                        </Input>
                                    </div>
                                </CardContent>
                            </Card>
                                <Card class="mt-4">
                                    <CardHeader>
                                        <CardTitle>Email & Call Audio</CardTitle>
                                        <CardDescription>
                                            Generated By ElevenLabs
                                        </CardDescription>
                                    </CardHeader>
                                    <CardContent class="space-y-4">

                                        <div class="grid gap-2">
                                            <audio controls>
                                                <source :src="page.props.url" type="audio/mpeg">
                                                Your browser does not support the audio element.
                                            </audio>                                        </div>
                                    </CardContent>
                                </Card>
                            </div>
                            <div>
                                <Card>
                                    <CardHeader>
                                        <CardTitle>Contact Summary</CardTitle>
                                        <CardDescription>
                                            Generated By AI
                                        </CardDescription>
                                    </CardHeader>
                                    <CardContent class="space-y-4">

                                        <div class="grid gap-2">
                                            <Label for="summary">Sumamry</Label>
                                            <Textarea id="bio" class="h-[350px]" :placeholder="contact.data.summary" />
                                        </div>
                                    </CardContent>
                                </Card>
                                <Card class="mt-4">
                                    <CardHeader>
                                        <CardTitle>Email & Call Script</CardTitle>
                                        <CardDescription>
                                            Generated By AI
                                        </CardDescription>
                                    </CardHeader>
                                    <CardContent class="space-y-4">

                                        <div class="grid gap-2">
                                            <Textarea id="bio" class="h-[450px]" :placeholder="contact.data.script.response" />
                                        </div>
                                    </CardContent>
                                </Card>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>
